version: "3"

services:
    app:
        build: .
        command: yarn dev
        volumes:
            - .:/usr/src/app
        links: 
            - postgres
        depends_on: 
            - postgres
        ports:
            - "3333:3333"
            
    postgres:
        image: postgres
        environment: 
            - POSTGRES_DB=swapi
            - POSTGRES_USER=postgres
            - POSTGRES_PASSWORD=docker
